name: warehouse-app

services:
  postgres-warehouse:
    image: postgres:17
    container_name: warehouse_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: warehouse_user
      POSTGRES_PASSWORD: warehouse_password
      POSTGRES_DB: warehouse_database
    ports:
      - "5432:5432"
    volumes:
      - warehouse_pgdata:/var/lib/postgresql/data

volumes:
  warehouse_pgdata:
